title: Spongebob-timecard-generator
description: A simple time card generator for the infamous sponebob timecards.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
